#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd 2D/

./Allclean
runApplication blockMesh
runApplication setRefinedFields
runApplication blastFoam
touch .foam

cd ../3D
./Allclean
runApplication blockMesh
runApplication rotateFields ../2D -centre '(0 0 5)' -sourceTime latestTime
touch .foam
# ----------------------------------------------------------------- end-of-file
